### ISSUE TITLE
Focusing doesn't work in Safari or Firefox

### ISSUE THREAD

**Issue by tannermann** [hteumeuleu/hocus-focus#5]
The website works perfectly in Chrome but is impossible to use in Safari or Firefox. When the page is first loaded the first square has focus. Pressing tab removes focus and new elements on the page cannot gain focus and no focus styles are visible.

PS: I love this project and share it with multiple people every year in October. Thank you for creating this.

**Comment by hteumeuleu** [comment]
Unless I misunderstood, that's… kind of the point. The games removes focus styles on purpose to make you realize their importance. I'm curious why that'd work differently in Chrome than in Firefox or Safari. Feel free to comment further if you feel I didn't get what you meant.

**Comment by hteumeuleu** [comment]
Ha, I see. I think Safari and Firefox don't use the tab key by default or don't navigate through all available controls. This should be consistent across all websites in your configuration. This article (in french) explains how to configure your system to work like Chrome: https://marieguillaumet.com/activer-la-prise-de-focus-dans-firefox-sur-macos/
