### ISSUE TITLE
Timer start bypass cheat

### ISSUE THREAD

**Issue by the-red-herring** [hteumeuleu/hocus-focus#8]
Hello :)

As of writing, the game as it hosted [here](https://focus.hteumeuleu.com/) has a bug where shift+tabbing at the start of every level will not start the timer.
This happens on Firefox 132.0b9 and also Chrome.

I suppose one way of fixing this from a js perspective could be to add an event listener for the user pressing tab or shift+tab.

If there's any other issue details I could provide lmk.

**Comment by hteumeuleu** [comment]
I’m okay with that :) The point of the game is to teach about keyboard focus. If you know enough that you can cheat your way through the game, that's great! Plus, I don't think there's any efficient way to detect this. (Listening for keyboard shortcuts can differ for every browser as it's customizable. And listening for a previous element focus would still count as cheating anyway I guess?) Thanks anyway for your interest and reporting this.
